Userfriendly\Bundle\SocialUserBundle\Entity\User:
    type: mappedSuperclass
    fields:
        usernameSlug:
            column: username_slug
            type: string
            length: 128
            unique: true
            gedmo:
                slug:
                    fields:
                        - username
        updatedAt:
            column: updated_at
            type: datetime
            gedmo:
                timestampable:
                    on: update
        createdAt:
            column: created_at
            type: datetime
            gedmo:
                timestampable:
                    on: create
##
## It is illegal to put an inverse side one-to-many or many-to-many association on mapped superclass:
##
#    oneToMany:
#        identities:
#            targetEntity: UserIdentity
#            mappedBy: user
#        emailChangeRequests:
#            targetEntity: UserEmailChangeRequest
#            mappedBy: user
#
##
## Ah well. Too bad.
##