
uf_profile_show:
    path:  /user/{username_slug}
    defaults:
        _controller: UserfriendlySocialUserBundle:Profile:show

uf_profile_edit:
    path:  /user/{username_slug}/edit
    defaults:
        _controller: UserfriendlySocialUserBundle:Profile:edit

uf_profile_username_available:
    path:  /user/{username_slug}/username-available
    defaults:
        _controller: UserfriendlySocialUserBundle:Profile:usernameAvailable

uf_profile_save_username:
    path:  /user/{username_slug}/change-username
    defaults:
        _controller: UserfriendlySocialUserBundle:Profile:saveUsername

uf_profile_save_password:
    path:  /user/{username_slug}/change-password
    defaults:
        _controller: UserfriendlySocialUserBundle:Profile:savePassword

uf_profile_request_change_email:
    path:  /user/{username_slug}/change-email
    defaults:
        _controller: UserfriendlySocialUserBundle:Profile:requestChangeEmail

uf_profile_confirm_change_email:
    path:  /confirm/change-email/{confirmation_token}
    defaults:
        _controller: UserfriendlySocialUserBundle:Profile:confirmChangeEmail
